//
//  ToDoListInteractor.swift
//  TodoList
//
//  Created by Mac on 21.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

/// Протокол интерактора экрана пользовательских задач
protocol ToDoListBusinessLogic {
	/// экран загрузился
	/// - Parameter request: запрос содержащий сообщение действительно ли экран загрузился
	func viewLoaded(request: ToDoList.Request)
	/// на ячейку нажали
	/// - Parameter request: запрос содержащие индекс нажатой ячейки
	func didTapOnCell(request: ToDoList.TapRequest)
}


/// Интерактор экрана пользовательских задач
class ToDoListInteractor: ToDoListBusinessLogic {
	/// презентер экрана пользовательских задач
	var presenter: ToDoListPresentationLogic?
	/// работник экрана пользовательских задач
	let worker: IToDoListWorker

	/// инициализирует интерактор с работником для обработки задач связанных с пользовательски вводом
	/// - Parameter worker: работник экрана пользовательских задач
	init(worker: IToDoListWorker) {
		self.worker = worker
	}

	func viewLoaded(request: ToDoList.Request) {
		let responce = ToDoList.Response(response: worker.mapViewData())
		presenter?.presentTable(responce: responce)
	}

	func didTapOnCell(request: ToDoList.TapRequest) {
		worker.checkTask(at: request.indexPath)
		let responce = ToDoList.TapResponse(response: worker.mapViewData())

		presenter?.renderAfterCellChecked(responce: responce)
	}
}
