//
//  LoginModels.swift
//  TodoList
//
//  Created by Mac on 21.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


/// модель для обработки задач связаных с логином
enum Login {
	/// модель запроса
	struct Request {
		/// логин введеный пользователем
		let login: String
		/// пароль введенный пользователем
		let password: String
	}
	/// модель ответа отправленный на запрос
	struct Response {
		/// открыт ли доступ
		let isAllowedAccess: Bool
	}
	/// модель для экрана логина
	struct ViewModel {
		/// можно ли двигаться на следующий экран
		let canMoveNext: Bool
	}
}

/// модель для обработки нажатия по экрану
enum Edit {
	/// модель для экрана логина
		struct ViewModel {
			/// закончить редактирование
			let endEditing: Bool
		}
}
