//
//  LoginInteractor.swift
//  TodoList
//
//  Created by Mac on 21.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// протокол интерактора экрана логина
protocol LoginBusinessLogic {
	/// произошло нажатие на логин
	/// - Parameter request: данные которые пришли вместе с нажатием
	func logInTapped(request: Login.Request)
	/// начались нажатия на экран
	func tochesBegan()
}

/// интерактор экрана логин
class LoginInteractor: LoginBusinessLogic {
	/// презентер экрана логин
	var presenter: LoginPresentationLogic?
	/// работник интерактора для обработки логики логина
	var worker: LoginWorker?

	func logInTapped(request: Login.Request) {
		worker = LoginWorker()
		guard let workerResult = worker?.isAllowed(data: request) else { return }

		let response = Login.Response(isAllowedAccess: workerResult)
		presenter?.deliver(response: response)
	}

	func tochesBegan() {
		let viewModel = Edit.ViewModel(endEditing: true)
		presenter?.hideKeyBoard(viewModel: viewModel)
	}
}
