//
//  LoginPresenter.swift
//  TodoList
//
//  Created by Mac on 21.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


/// протокол презентера экрана логина
protocol LoginPresentationLogic {
	
	/// передать ответ от интерактора
	/// - Parameter response: ответ
	func deliver(response: Login.Response)
	
	/// скрыть клавиатуру
	/// - Parameter viewModel: модель содержит bool для скрытия
	func hideKeyBoard(viewModel: Edit.ViewModel)
}


/// Класс презентер экрана логина
class LoginPresenter: LoginPresentationLogic {
	typealias LoginLogic = LoginEditingLogic & LoginDisplayLogic

	/// экран логина
	weak var viewController: LoginLogic?

	func deliver(response: Login.Response) {
		let viewModel = Login.ViewModel(canMoveNext: response.isAllowedAccess)
		viewController?.route(viewModel: viewModel)
	}

	func hideKeyBoard(viewModel: Edit.ViewModel) {
		viewController?.endEditing(viewModel: viewModel)
	}
}
